// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe45L2ZDk720w14nQlif0OzW5HB7_F-TY',
    appId: '1:979195398227:web:f9c2412e31ee05e86e5ea6',
    messagingSenderId: '979195398227',
    projectId: 'phonenumbauth-f770d',
    authDomain: 'phonenumbauth-f770d.firebaseapp.com',
    storageBucket: 'phonenumbauth-f770d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz72avyCwms2d9GVYYdkVVy-Y6ig_LrV4',
    appId: '1:979195398227:android:bcc17496333659a86e5ea6',
    messagingSenderId: '979195398227',
    projectId: 'phonenumbauth-f770d',
    storageBucket: 'phonenumbauth-f770d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4sEC0EQ0yP4WrF9feaZpRJozEBsJtzQM',
    appId: '1:979195398227:ios:8672b0467f36c8e66e5ea6',
    messagingSenderId: '979195398227',
    projectId: 'phonenumbauth-f770d',
    storageBucket: 'phonenumbauth-f770d.appspot.com',
    iosBundleId: 'com.example.testfirebasapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4sEC0EQ0yP4WrF9feaZpRJozEBsJtzQM',
    appId: '1:979195398227:ios:8672b0467f36c8e66e5ea6',
    messagingSenderId: '979195398227',
    projectId: 'phonenumbauth-f770d',
    storageBucket: 'phonenumbauth-f770d.appspot.com',
    iosBundleId: 'com.example.testfirebasapp',
  );
}
